import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
export default function Home() {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div>

{/* <p className={styles.extraGreen}>I am a super cool software engineer now. I make super cool sytuff with</p> */}
<div >


    <style jsx>{`


          .margin-bottom {
            margin-bottom : 20px
        }
        .whiteText {
            color: white
        }
        .orangeText {
            color: #748DA6
        }
        p {
            // font-size: 70px
        }
        h1 {
            font-size: 70px
        }
        .underline{
            font-style: underline
        }
        .margin-left {
            margin-left: 20px
        }
        .flex {
            display: flex;
            justify-content: space-evenly
        }
        h2 {
            font-size: 35px
        }
        h4 {
            font-size: 45px
        }
        center {
            text-align: center

        }
        .list{
            list-style: none
        }
        .flex-space {
            display: flex;
            justify-content: space-evenly
        }
        .mt{
            margin-top: 60px;

        }
        .mb{
            margin-bottom: 100px
        }
        .gold {
            color: #ECB365
        }
        .bg {
            background-color: #064663;
            color: #064663
        }
        .margin-right {
            margin-right: 20px
        }
        .mr {
          margin-right: 200px
      }
      .ml {
        margin-left: 200px
    }
    @media (max-width: 600px) {
      .flex {
        display: grid

      }
    }

    `}</style>
<h1 className='whiteText margin-left'>John Dercole</h1>
<h4 className='orangeText margin-left'>Full Stack Software Engineer</h4>
<div className='bg mt'>
<div className='bg'>
    <h3 className='bg'>g</h3>
</div>

<div className='margin-left flex'>

</div>
    <h4 className='gold underline margin-left'> About me</h4>
    <h3 className='whiteText margin-left margin-right'>I am a full stack software engineer with a passion for design, music and interactive features. I prioritize writing clean code that is maintainable and easy for other engineers to use. Providing customized solutions to ever changing problems is my favorite part of being an engineer.</h3>
    <h2 className='whiteText'><a href='https://github.com/GianlorenzoDercole'> View My GitHub</a></h2>
    <div className='bg'>
    <h3 className='bg'>g</h3>
</div>

    </div>

</div>




{/* <img src='/killer-bunny.jpg' alt='vil'/> */}

</div>
      </main>
    </div>
  )
}
//


//////////////////////////////////////











// import Image from 'next/image'

// import styles from '../styles/About.module.css'
// export default function About() {
//     return (
//         <div>
//             <h1>about</h1>
//             <p className={styles.extraGreen}>I am a super cool software engineer now. I make super cool sytuff with</p>
//             <div>
//                 <style jsx>{`
//                     .orangeText {
//                         color: orange
//                     }
//                     p {
//                         font-size: 70px
//                     }
//                 `}</style>
//             <p className='orangeText'>I like to code</p>
//             </div>

//             <Image
//                 src='/killer-bunny.jpg'
//                 alt='my fav'
//                 width={500}
//                 height={500}
//             />

//             {/* <img src='/killer-bunny.jpg' alt='vil'/> */}
//             <Image
//                 src='https://placekitten.com/300/300'
//                 alt='u'
//                 width={500}
//                 height={500}
//             />
//         </div>
//     )
// }
