












import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Mobile.module.css'
import Link from 'next/link'
export default function Home() {
  return (
    <div >
      <Head>
        <title>John Dercole Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>

        <div>
{/* <p className={styles.extraGreen}>I am a super cool software engineer now. I make super cool sytuff with</p> */}
<div >


    <style jsx>{`
          .margin-bottom {
            margin-bottom : 20px
        }
        .whiteText {
            color: white
        }
        .orangeText {
            color: #748DA6
        }
        .blueText{
          color: #00ADB5
        }
        p {
            // font-size: 70px
        }
        h1 {
            font-size: 70px
        }
        .underline{
            font-style: underline;
        }
        .margin-left {
            margin-left: 20px
        }
        .flex {
            display: flex;
            justify-content: space-evenly
        }
        h2 {
            font-size: 35px
        }
        h4 {
            font-size: 45px
        }
        center {
            text-align: center
        }
        .list{
            list-style: none
        }
        .flex-space {
            display: flex;
            justify-content: space-evenly
        }
        .mt{
            margin-top: 250px;
        }
        .mtsus {
          margin-top: 10px;
        }
        .mts {
          margin-top: 100px
        }
        .mb{
            margin-bottom: 150px
        }
        .mbl{
            margin-bottom: 81px
        }
        .gold {
            color: #ECB365
        }
        .bg {
            background-color: white;
            color: #222831
        }
        .margin-right {
            margin-right: 20px
        }
        .mr {
          margin-right: 200px
      }
      .ml {
        margin-left: 200px
    }
    @media (max-width: 600px) {
      .flex {
        display: grid;
        @media (max-width: 800px) {













      }
      .ml{
        margin-right: 200px;
      }
      .mr {
        margin-left: 20px;
      }
      .b{
        height: 200px;
      }
      .left{
        text-align: left;
      }
      .underline {
        text-decoration: underline;
      }
      .darkgrey {
        color: #222831;
      }
    }
    `}</style>

    <div className={styles.mt}>
  <div className='flex mb'>
    <div className={styles.left}>
      <h1 className='whiteText '>John Dercole</h1>

      <h2 className='whiteText'>Full Stack Software Engineer</h2>
      <div className={styles.ms}>
      <a href='#projects'>
        <button className={styles.button} >Projects</button>
      </a>
      </div>
    </div>
    <div>
    <Image
                    src='/im.png'
                    height={500}
                    width={600}
                />
    </div>
  </div>
  </div>

<div id='about' className='bg'>
<h3 className='whiteText'>-</h3>
<div className={styles.mll}>
<div className='bg'>
<div className={styles.left}>
      <h1 >About Me</h1>
      <hr className={styles.line}></hr>
      {/* <p className='whiteText'>-</p> */}
      <p className='blueText'></p>
      <p className={styles.mr}>I am a full stack software engineer with a passion for design, music and interactive features.
        I prioritize writing clean code that is maintainable and easy for other engineers to use.  Providing customized solutions to ever changing
      problems is my favorite part of being a software engineer.</p>
      <p className='whiteText'>-</p>
      <Link href='/resume'><button className={styles.slbutton}>Resume</button></Link>
      <a href='https://github.com/GianlorenzoDercole'><button className={styles.srbutton}>GitHub</button></a>

    </div>
    </div>

</div>
<h2 className='whiteText'>-</h2>
</div>
<h3 id='projects' className={styles.darkgrey}>-</h3>

<div className={styles.left}>
<div className={styles.mll}>
  <h1  className='whiteText'>Projects</h1>
  </div>
  <div className={styles.mll}>
  <hr className={styles.line}></hr>
  </div>
  {/* <p className='ml blueText'>________________________________________________</p> */}

</div>
<h3 className={styles.darkgrey}>-</h3>

<div className='flex'>

<div className=' margin-bottom'>
<a href='https://gianlorenzodercole.github.io/dragon_flight/'>
<Image
        src='/agame.png'
        alt='dragon flight game'
        width={300}
        height={300}
    />
</a>

    <h3 className='whiteText'>Dragon Flight</h3>
    <p className='whiteText'>2D game made using HTML canvas</p>
    <a href='https://gianlorenzodercole.github.io/dragon_flight_2/' className='whiteText'><button className={styles.smallbutton}>Try it</button></a>

    <a href='https://github.com/GianlorenzoDercole/dragon_flight_2' className='whiteText'><button className={styles.smallbuttonr}>GitHub</button></a>

    {/* <p className={styles.ulh}><a href='https://gianlorenzodercole.github.io/dragon_flight/' className='whiteText'>View on GitHub</a></p> */}

    {/* <p><a href='https://gianlorenzodercole.github.io/dragon_flight/' className='whiteText'>Try it</a></p> */}


</div>


<div className=' margin-bottom'>
    <a href='https://62bf3556f83fa3115ff23304--reliable-bombolone-dbc4f8.netlify.app/'>
    <Image
        src='/pic.png'
        alt='pic it up'
        width={300}
        height={300}
    />
    </a>
    <h3 className='whiteText'>Pic It Up</h3>
    <p className='whiteText'>Instagram clone built with a team of four</p>
    <a href='https://62bf3556f83fa3115ff23304--reliable-bombolone-dbc4f8.netlify.app/' className='whiteText'><button className={styles.smallbutton}>Try it</button></a>
    <a href='https://github.com/GianlorenzoDercole/instagram-clone-client' className='whiteText'><button className={styles.smallbuttonr}>GitHub</button></a>
</div>
{/* https://62bf3556f83fa3115ff23304--reliable-bombolone-dbc4f8.netlify.app/ */}

{/* https://62bf355dbab5b313b12cda05--inspiring-taiyaki-bccd73.netlify.app/ */}
<div className=' margin-bottom'>
<a href='https://github.com/GianlorenzoDercole/pypong'>
<Image
        src='/pypong.png'
        alt='dragon flight game'
        width={300}
        height={300}
    />
</a>

    <h3 className='whiteText'>PyPong</h3>
    <p className='whiteText'>Player vs AI Pong built with Python</p>
    {/* <a href='https://gianlorenzodercole.github.io/dragon_flight/' className='whiteText'><button className={styles.smallbutton}>Try it</button></a> */}

    <a href='https://github.com/GianlorenzoDercole/pypong' className='whiteText'><button className={styles.smallbuttonc}>GitHub</button></a>

    {/* <p className={styles.ulh}><a href='https://gianlorenzodercole.github.io/dragon_flight/' className='whiteText'>View on GitHub</a></p> */}

    {/* <p><a href='https://gianlorenzodercole.github.io/dragon_flight/' className='whiteText'>Try it</a></p> */}

</div>

<div className=' margin-bottom'>
    <a href='https://github.com/GianlorenzoDercole/Forza_Favorites'>
    <Image
        src='/fof.png'
        alt='forza favorites app'
        width={300}
        height={300}
    />
    </a>
    <h3 className='whiteText'>Forza Favorites</h3>
    <p className='whiteText'>Full stack app built using Express and SQL</p>
    {/* <a href='https://forza-favorites.herokuapp.com/' className='whiteText'><button className={styles.smallbutton}>Try it</button></a> */}
    <a href='https://github.com/GianlorenzoDercole/Forza_Favorites' className='whiteText'><button className={styles.smallbuttonc}>GitHub</button></a>
</div>


</div>


<h2 className={styles.darkgrey}>-</h2>


<div className='bg'>

    <h3 className='whiteText'>-</h3>
    <div className={styles.mll}>
    <div className={styles.left}>
      <h1>Tech Stack</h1>
      </div>
      <div >
        <hr className={styles.longline}></hr>
      </div>
    </div>

    <div className=' flex-space mts'>
                <div>
                <Image className='margin-left'
                    src='/javascript.png'
                    height={60}
                    width={60}
                />
                <p>Javascript</p>
                </div>
                <div>
                <Image className='margin-left'
                    src='/html5.png'
                    height={60}
                    width={60}
                />
                <p>HTML</p>
                </div>

                <div>
                <Image
                    src='/css3.png'
                    height={60}
                    width={60}
                />
                <p>CSS</p>
                </div>
                <div>
                <Image className='margin-left'
                    src='/react.png'
                    height={60}
                    width={60}
                />
                <p>React</p>
                </div>
                <div>
                <Image className='margin-left'
                    src='/python.png'
                    height={60}
                    width={60}
                />
                <p>Python</p>
                </div>
  </div>

  <div className=' flex-space mts'>
                <div>
                <Image className='margin-left'
                    src='/sql-retro.png'
                    height={60}
                    width={60}
                />
                <p>SQL</p>
                </div>
                <div>
                <Image className='margin-left'
                    src='/mongodb.png'
                    height={60}
                    width={60}
                />
                <p>MongoDB</p>
                </div>
                <div>
                <Image className='margin-left'
                    src='/postman.png'
                    height={60}
                    width={60}
                />
                <p>Postman</p>
                </div>
                <div>
                <Image className='margin-left'
                    src='/django.png'
                    height={60}
                    width={60}
                />
                <p>Django</p>
                </div>
                <div>
                <Image className='margin-left'
                    src='/node-js.png'
                    height={60}
                    width={60}
                />
                <p>Node.js</p>
                </div>
</div>
<div>
  <h1 className='whiteText'>-</h1>
</div>
</div>

<div>

  <div className={styles.left}>
  <div className={styles.mll}>
        <h1 id='contact' className=' whiteText'>Contact</h1>


          <hr className={styles.line}></hr>

        <h3 className=' whiteText'>johndercole01@gmail.com</h3>
        <h3 className='  whiteText'>(860) 689 3058</h3>
        <div className='  whiteText'>
          <Link href='/resume'>
          <h3 className={styles.underline}>Resume</h3>
          </Link>

        </div>
        <div className=' mbl whiteText'>
          <a href='https://www.linkedin.com/in/johndercole01/'>
          <Image
                    src='/Linkedin-Logo-grey.png'
                    height={30}
                    width={30}
                />
          </a>

        <div className='mtsus'>
          <a href='https://github.com/GianlorenzoDercole'>
          <Image
                    src='/GitHub-Mark.png'
                    height={30}
                    width={30}
                />
          </a>
          </div>
        </div>


        </div>

  </div>

</div>

</div>
{/* <img src='/killer-bunny.jpg' alt='vil'/> */}

</div>
      </main>
    </div>
  )
}
//


//////////////////////////////////////
/////////////////////////////////////




/////////////////


// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../styles/Home.module.css'
// export default function Home() {
//   return (
//     <div >
//       <Head>
//         <title>John Dercole Portfolio</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>
//       <main>

//         <div>

// {/* <p className={styles.extraGreen}>I am a super cool software engineer now. I make super cool sytuff with</p> */}
// <div >


//     <style jsx>{`


//           .margin-bottom {
//             margin-bottom : 20px
//         }
//         .whiteText {
//             color: white
//         }
//         .orangeText {
//             color: #748DA6
//         }
//         p {
//             // font-size: 70px
//         }
//         h1 {
//             font-size: 70px
//         }
//         .underline{
//             font-style: underline
//         }
//         .margin-left {
//             margin-left: 20px
//         }
//         .flex {
//             display: flex;
//             justify-content: space-evenly
//         }
//         h2 {
//             font-size: 35px
//         }
//         h4 {
//             font-size: 45px
//         }
//         center {
//             text-align: center

//         }
//         .list{
//             list-style: none
//         }
//         .flex-space {
//             display: flex;
//             justify-content: space-evenly
//         }
//         .mt{
//             margin-top: 60px;

//         }
//         .mb{
//             margin-bottom: 100px
//         }
//         .gold {
//             color: #ECB365
//         }
//         .bg {
//             background-color: #064663;
//             color: #064663
//         }
//         .margin-right {
//             margin-right: 20px
//         }
//         .mr {
//           margin-right: 200px
//       }
//       .ml {
//         margin-left: 200px
//     }
//     @media (max-width: 600px) {
//       .flex {
//         display: grid

//       }
//       .ml{
//         margin-right: 20px;
//       }
//       .mr {
//         margin-left: 20px;
//       }
//     }

//     `}</style>
// <h1 className='whiteText margin-left'>John Dercole</h1>
// <h4 className='orangeText margin-left'>Full Stack Software Engineer</h4>
// <div className='bg mt'>
// <div className='bg'>
//     <h3 className='bg'>g</h3>
// </div>
// <h4 className='gold underline margin-left mt'>Check out some of my recent projects</h4>
// <div className='mt'></div>
// <div className='margin-left flex'>
// <div className='center margin-bottom'>
//     <Image className='margin-left'
//         src='/agame.png'
//         alt='dragon flight game'
//         width={300}
//         height={300}
//     />
//     <h3 className='whiteText'>Dragon Flight</h3>
//     <p className='whiteText'>2D game made using html canvas</p>
//     <p><a href='https://gianlorenzodercole.github.io/dragon_flight/' className='orangeText'>Try it</a></p>
//     <a href='https://github.com/GianlorenzoDercole/dragon_flight' className='orangeText'>View on github</a>
// </div>
// <div className='margin-left margin-bottom'>
//     <Image className='margin-left'
//         src='/fof.png'
//         alt='forza favorites app'
//         width={300}
//         height={300}
//     />
//     <h3 className='whiteText'>Forza Favorites</h3>
//     <p className='whiteText'>Full stack app built using express and SQL</p>
//     <p><a href='https://forza-favorites.herokuapp.com/' className='orangeText'>Try it</a></p>
//     <a href='https://github.com/GianlorenzoDercole/Forza_Favorites' className='orangeText'>View on github</a>
// </div>
// <div className='margin-left margin-right margin-bottom'>
//     <Image className='margin-left'
//         src='/pic.png'
//         alt='pic it up'
//         width={300}
//         height={300}
//     />
//     <h3 className='whiteText'>Pic It Up</h3>
//     <p className='whiteText'>Instagram clone built with a team of four</p>
//     <p><a href='https://62bf355dbab5b313b12cda05--inspiring-taiyaki-bccd73.netlify.app/' className='orangeText'>Try it</a></p>
//     <a href='https://github.com/GianlorenzoDercole/instagram-clone-client' className='orangeText'>View on github</a>
// </div>

// </div>
// <div className='bg'>
//     <h3 className='bg'>g</h3>
// </div>
// </div>
// <div className='mt'></div>
// <h4 className='gold underline'> Tech stack</h4>
// <div className='margin-left flex-space'>
//             <Image className='margin-left'
//                     src='/javascript.png'
//                     height={30}
//                     width={30}
//                 />
//                 <Image className='margin-left'
//                     src='/html5.png'
//                     height={30}
//                     width={30}
//                 />

//             <Image
//                     src='/css3.png'
//                     height={30}
//                     width={30}
//                 />
//                 <Image className='margin-left'
//                     src='/python.png'
//                     height={30}
//                     width={30}
//                 />
//                 <Image className='margin-left'
//                     src='/react.png'
//                     height={30}
//                     width={30}
//                 />
//                 {/* <Image className='margin-left'
//                     src='/node-js.png'
//                     height={30}
//                     width={30}
//                 /> */}

//                 </div>
//                 <div className='margin-left flex-space'>
//                     <h2></h2>
//                 </div>
//                 <div className='margin-left flex-space'>
//                 <Image className='margin-left'
//                     src='/sql-retro.png'
//                     height={30}
//                     width={30}
//                 />
//                 <Image className='margin-left'
//                     src='/mongodb.png'
//                     height={30}
//                     width={30}
//                 />
//                 <Image className='margin-left'
//                     src='/postman.png'
//                     height={30}
//                     width={30}
//                 />
//                 <Image className='margin-left'
//                     src='/django.png'
//                     height={30}
//                     width={30}
//                 />
//                 <Image className='margin-left'
//                     src='/node-js.png'
//                     height={30}
//                     width={30}
//                 />
//                 {/* <Image className='margin-left'
//                     src='/node-js.png'
//                     height={30}
//                     width={30}
//                 /> */}
//                 </div>
//     <div className='mt'></div>
//     <div className='bg'>
//     <div className='bg'>
//     <h3 className='bg'>g</h3>
// </div>
//     <h4 className='gold underline '> About me</h4>
//     <div>

//     <h3 className='whiteText ml mr'>I am a full stack software engineer with a passion for design, music and interactive features. I prioritize writing clean code that is maintainable and easy for other engineers to use. Providing customized solutions to ever changing problems is my favorite part of being an engineer.</h3>
//     {/* <Image className=' margin-right'
//         src='/agame.png'
//         alt='dragon flight game'
//         width={300}
//         height={300}
//     /> */}
//     </div>

//     <h2 className='whiteText'><a href='https://github.com/GianlorenzoDercole'> View My GitHub</a></h2>
//     <div className='bg'>
//     <h3 className='bg'>g</h3>
// </div>

//     </div>
//     <h1 className='whiteText'>Contact</h1>
//     <h3 className='whiteText'>johndercole01@gmail.com</h3>
//     <h3 className='whiteText'>860 689 3058</h3>
//     <h3><a className='whiteText' href='https://github.com/GianlorenzoDercole'>github</a></h3>
//     <h3><a className='whiteText' href='https://www.linkedin.com/in/john-dercole-92501223b/'>linkedin</a></h3>

// </div>




// {/* <img src='/killer-bunny.jpg' alt='vil'/> */}

// </div>
//       </main>
//     </div>
//   )
// }
// //


// //////////////////////////////////////
// /////////////////////////////////////
